### ISSUE TITLE
IO error when sending several metrics per second with StatsClient

### ISSUE THREAD

**Issue by mossprescott** [iand675/datadog#20]
I'm seeing the following error printed to stderr, and no metrics recorded, apparently when I send more than about 50 metrics at a rate of about 5 per second: `<socket: 14>: hPutBuf: resource exhausted (Message too long)`

I can make the error go away by either reducing the total number of metrics to about 50 or so, or by inserting a one second delay after each one is sent, and either way I then see metrics appear in Datadog. The metrics are Timer values, all with the same name, which is about 20 characters, and a single tag with about 10 different values, naming different queries that I'm timing. Removing the tag doesn't seem to have any effect.

I'm sending these via Datadog Agent 6.1.4, with the default configuration except for supplying `api_key`. I briefly tried increasing the buffer sizes in the dogstatsd config, but that doesn't seem to help. In infer that the problem is on the Haskell side of the UDP connection, but I don't see anyway to configure it to handle more volume, if indeed that is the problem. 

It seems like this kind of metric at this rate is well within what Datadog/statsd should be able to handle, so hopefully I'm doing something wrong.

Unfortunately I can't share the code that's provoking the problem. If it seems like it would help, I can try to reduce it to a minimal test program.

**Comment by iand675** [comment]
Thanks for the report! Sorry to hear that you're encountering issues/ I do indeed agree that you're probably seeing things exceed the UDP packet size, which would be a bug in the client. Unfortunately I think solving the issue is probably going to require some fundamental changes in the client to consistently get it right. A few things you might try in the interim: 

- reduce the `reaperDelay` to less than one second. 
- use multiple `StatsClient`s since they'll each have their own UDP handle they send stats from.
